### ISSUE TITLE
keep classes of columns

### ISSUE THREAD

**Issue by bnicenboim** [DiskFrame/disk.frame#379]
Hi!
Would it be possible that disk frame would not remove the (custom) classes (and attributes) of the columns of the data frame?
See below, I add a class to a column and it disappears.

```
dt <- data.table(x= 1:10, y= 1:10)
class(dt$x) <- c(class(dt$x), "myclass")
class(dt$x)
## [1] "integer" "myclass"
df <- as.disk.frame(dt)
dt2 <- as.data.table(df)
class(dt2$x)
## [1] "integer"
```

**Comment by xiaodaigh** [comment]
Hmm, this will be technically quite hard. I will close this issue for now as I don't really see that I will ever implement it.
