### ISSUE TITLE
solve function doesn't work with this package for large observation of matrix

### ISSUE THREAD

**Issue by rohitwalthare** [DiskFrame/disk.frame#383]
I am trying to use the solve function with the matrix which consists of 49543x16 observation and trying to use the following command but it isn't working "diag(X %*% solve(XX) %*% t(X))" also the error is similar with memory allocation as "cannot allocate vector of size ..."

**Comment by xiaodaigh** [comment]
Disk.frame can’t be used to solve massive matrix problems like this unfortunately. 

Only table problems.

**Comment by rohitwalthare** [comment]
is there any other possible solution for this to solve, cause I'm trying to use whatever the available solution we have over the web and tried basically, so thought to give the suggestion for further development?

really appreciate your quick reply to the earlier thread and thank you.

**Comment by xiaodaigh** [comment]
Not sure. But I imagine you would need some big memory package Check bigmemory? Or you might need some disk based mmapping approach. Yeah, I am probably not much help beyond that.

**Comment by rohitwalthare** [comment]
thank you for your suggestions, though package bigmemory didn't help.
